site_name: Kor2Num
theme:
  name: material

nav:
  - Home: index.md
  - Installation: installation.md
  - Getting Started: getting_started.md
  - File Structure: file_structure.md
  - File Description: file_description.md
